export const rawOrders =[
    {
      id: "1",
      table: "Table 12",
      time: "New",
      status: "Pending",
      items: [
        { name: "Ofada Rice", quantity: "3 Plates" },
        { name: "Vegetable Soup", quantity: "1 Plate" },
        { name: "Peppered Chicken", quantity: "5 Plates e" },
        { name: "Jollof Rice", quantity: "1 Plate" },
        { name: "Pounded Yam", quantity: "1 Plate " },
        { name: "Beef Burger", quantity: "3 Plates" },
      ],
      total: "₦300,000",
      date: "15/04/2025",
      isExpanded: false,
    },
    {
      id: "2",
      table: "Table 04",
      time: "08:25 AM",
      status: "Paid",
      items: [],
      total: "",
      date: "15/04/2025",
      isExpanded: false,
    },
    {
      id: "3",
      table: "Table 02",
      time: "08:25 AM",
      status: "Paid",
      items: [],
      total: "",
      date: "15/04/2025",
      isExpanded: false,
    },
    {
      id: "4",
      table: "Table 17",
      time: "08:25 AM",
      status: "Paid",
      items: [],
      total: "",
      date: "15/04/2025",
      isExpanded: false,
    },
  ]