import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const privyId = process.env.NEXT_PUBLIC_PRIVY_APP_ID || '';
  const privyClientId = process.env.NEXT_PUBLIC_PRIVY_CLIENT_ID || '';
  const mainnetRPC = process.env.NEXT_PUBLIC_MANNIET_RPC || '';

  if (!privyId || !privyClientId) {
    throw new Error('Privy App ID or Client ID is missing. Please check your environment variables.');
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers privyId={privyId} privyClientId={privyClientId} mainnetRPC={mainnetRPC}>
            {children}
        </Providers>
      </body>
    </html>
  );
}
